# Lab 1: Introduction to OpenCV

The goal of this first lab is to present a small introduction to image processing using OpenCV. In each section, you can find:
* a small example - analyse the code and try it
* some exercises

In [ ]:
# Requirements for this tutorial
#! pip install opencv-python
#! pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.3/37.3 MB 2.6 MB/s eta 0:00:0000:0100:01


In [ ]:
# If you prefer, you can convert this notebook to a Python script by uncommenting the following command
#! pip install nbconvert
#! jupyter nbconvert --to script 01-introduction.ipynb

[NbConvertApp] Converting notebook 01-introduction.ipynb to script
[NbConvertApp] Writing 6541 bytes to 01-introduction.py


In [2]:
import cv2
import numpy as np
import os

dataDir = 'images'

A reference table with some useful functions:

| Function | Description |
| ------------- | ------------- |
| **Low-level NumPy** | |
| `x = np.array(list)` | Converts Python list to `ndarray` |
| `x = np.zeros((80, 80, 3))` | Create an array 80x80x3 of zeros (i.e., a black image). |
| `x = np.ones((80, 80, 3))` | Same with ones. |
| `x = np.random.rand((80, 80, 3))` | Same but each value is an uniform sample from [0,1]. |
| `x = np.random.randn((80, 80, 3))` | Same but each value is a Gaussian sample from N(0,1). |
| `print(x.shape)` | Print the shape of the `ndarray`. |
| **Arithmetic** | |
| `x[:, :, 0]` | Access the first slice of the third-axis (i.e., if `x` is an image with format BGR, this would be the blue channel. |
| `x += 50` | Adds 50 to all pixels. |
| `x[:, :, 1] *= 0.5` | Divides the green channel by 2. |
| **OpenCV2 basic functions** | |
| `img = cv2.imread(filename)` | Opens the image from the disk given by filename as a `ndarray`. |
| `cv2.imwrite(filename, img)` | Save the given image in the disk with the given filename. |
| `cv2.imshow(window_name, img)` | Open the given image in a window. |
| `cv2.destroyWindow(window_name)` | Destroys the window. |
| **OpenCV2 color conversion** | |
| `cv2.cvtColor(img, cv2.COLOR_BGR2RGB)` | Converts the color format. |
| `cv2.cvtColor(img, cv2.COLOR_BGR2HSV)` | |
| `cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)` | |
| **OpenCV2 user interaction** | |
| `cv2.setMouseCallback(window_name, callback)` | Calls the given callback function whenver user interacts with the window. |
| `cv2.selectROI(window_name, img)` | Asks the user to select a part of the image and returns that. |
| `key = cv2.waitKey(0)` | Waits until the user presses a key. |
| `key = cv2.waitKey(delay)` | Wait until the user presses a key or a certain delay passes (in seconds). |

### 1. Images – read, write and display; ROIs

In [3]:
# Opening an image
img = cv2.imread(os.path.join(dataDir, 'ml.jpg'))

# Showing the image
#cv2.imshow("ml.jpg", img)

#cv2.waitKey(0)

# Close the window after user pressed a key
#cv2.destroyWindow("ml.jpg")

In [4]:
# Check image size
h, w, c = img.shape
print(f'height: {h}')
print(f'width: {w}')
print(f'channels: {c}')

height: 380
width: 308
channels: 3


In [5]:
# Saving image in bmp format
cv2.imwrite('ml_new.bmp', img)

True

Exercise 1.1 - When the user moves the mouse, print the coordinate and RGB component of the pixel under the cursor. When the user clicks on a pixel, modify that pixel to blue.

In [6]:
# TODO
def mouse_event(event, x, y, flags, param):
    if event == cv2.EVENT_MOUSEMOVE:
        # Get the pixel value at (x, y)
        b, g, r = img[y, x]  # OpenCV uses BGR format
        print(f"Coordinates: ({x}, {y}) - RGB: ({r}, {g}, {b})")
    
    elif event == cv2.EVENT_LBUTTONDOWN:
        # Change the pixel color to blue
        img[y, x] = [255, 0, 0]  # BGR for blue
        cv2.imshow("Image", img)

# Create a window and set the mouse callback function
cv2.imshow("Image", img)
cv2.setMouseCallback("Image", mouse_event)
cv2.waitKey(0)

#Close the window after user pressed a key
cv2.destroyWindow("ml.jpg")
print("Done")

Coordinates: (250, 213) - RGB: (128, 131, 124)
Coordinates: (237, 210) - RGB: (255, 255, 255)
Coordinates: (202, 203) - RGB: (141, 160, 128)
Coordinates: (197, 201) - RGB: (238, 252, 227)
Coordinates: (181, 196) - RGB: (236, 247, 241)
Coordinates: (170, 191) - RGB: (251, 255, 254)
Coordinates: (167, 190) - RGB: (255, 255, 255)
Coordinates: (155, 184) - RGB: (255, 255, 255)
Coordinates: (150, 182) - RGB: (255, 255, 255)
Coordinates: (148, 181) - RGB: (255, 255, 255)
Coordinates: (144, 179) - RGB: (255, 255, 255)
Coordinates: (143, 178) - RGB: (253, 253, 251)
Coordinates: (142, 177) - RGB: (248, 248, 246)
Coordinates: (141, 177) - RGB: (255, 255, 255)
Coordinates: (141, 177) - RGB: (255, 255, 255)
Coordinates: (141, 177) - RGB: (255, 255, 255)
Coordinates: (147, 177) - RGB: (255, 255, 255)
Coordinates: (153, 177) - RGB: (255, 255, 255)
Coordinates: (169, 177) - RGB: (255, 255, 255)
Coordinates: (176, 177) - RGB: (255, 255, 255)
Coordinates: (191, 178) - RGB: (255, 255, 255)
Coordinates: 

Exercise 1.2 - Allow the user to select a region of interest (ROI) in the image, by clicking on two points that identify two opposite corners of the selected ROI, and save the ROI into another file.

In [9]:
# TODO

X, Y, W, H = cv2.selectROI("Image", img)

print("First point: ({}, {})".format(X, Y))
print("Second point: ({}, {})".format(X + W, Y + H))

rect= img[Y:Y+H, X:X+W]
cv2.imshow("ROI", rect)

cv2.waitKey(0)
cv2.destroyWindow("ROI")
#Close the window after user pressed a key

cv2.imwrite("roi.bmp",rect)

Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
First point: (39, 49)
Second point: (278, 305)


True

### 2. Images – representation, grayscale and color, color spaces

In [4]:
# Create a white image
m = np.ones((100,200,1), np.uint8)

# Change the intensity to 100
m = m * 100

# Display the image
cv2.imshow('Grayscale image', m)
cv2.waitKey(0)
cv2.destroyWindow('Grayscale image')

In [ ]:
# Draw a line with thickness of 5 px
cv2.line(m, (0,0), (100,200), 255, 5)
cv2.line(m, (200, 0), (0, 100), 255, 5)
cv2.imshow('Grayscale image with diagonals', m)
cv2.waitKey(0)
cv2.destroyWindow('Grayscale image with diagonals')

Exercise 2.1 - Create a color image with 100(lines)x200(columns) pixels with yellow color. Then draw two diagonal lines across the image, one in red color, the other in blue color. Display the image.

In [9]:
# TODO
m= np.ones((100,200,3), np.uint8)

m[:,:,0]=0
m[:,:,1]=255
m[:,:,2]=255
cv2.line(m, (0,0), (200,100), (255,0,0), 5)
cv2.line(m, (200, 0), (0, 100), (0,0,255), 5)
cv2.imshow('Yellow image with diagonals', m) 
cv2.waitKey(0)
cv2.destroyWindow('Yellow image')


KeyboardInterrupt: 

Exercise 2.2 - Read any color image, in RGB format, display it in one window, convert it to grayscale, display the grayscale image in another window and save the grayscale image to a different file

In [ ]:
# TODO

Exercise 2.3 - Split the 3 RGB channels and show each channel in a separate window. Add a constant value to one of the channels, merge the channels into a new color image and show the resulting image.

In [ ]:
# TODO

Exercise 2.4 - Convert the image to HSV, split the 3 HSV channels and show each channel in a separate window. Add a constant value to the saturation channel, merge the channels into a new color image and show the resulting image.

In [ ]:
# TODO

### 3. Video – acquisition and simple processing

In [ ]:
# Define a VideoCapture Object
cap = cv2.VideoCapture(0)
if not cap.isOpened():
    print("Cannot open camera")
    exit()

frame_nr = 0
while True:
    # Capture frame-by-frame
    ret, frame = cap.read()

    # If frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break

    # Display the resulting frame
    cv2.imshow('webcam', frame)

    # Wait for user to press s to save frame
    if cv2.waitKey(1) == ord('s'):
        frame_name = 'frame' + str(frame_nr) + '.png'
        cv2.imwrite(frame_name, frame)
        cv2.imshow("Saved frame: " + frame_name, frame)
        cv2.waitKey(0)
        cv2.destroyWindow("Saved frame: " + frame_name)

    # Wait for user to press q to quit
    if cv2.waitKey(1) == ord('q'):
        break

    frame_nr += 1

# When everything is done, release the capture
cap.release()
cv2.destroyAllWindows()

Exercise 3.1 - Using the previous example as the baseline, implement a script that acquires the video from the webcam, converts it to grayscale, and shows the frames in binary format (i.e. the intensity of each pixel is 0 or 255); use a threshold value of 128.

In [ ]:
# TODO

Exercise 3.2 - Implement a simple detection/tracking algorithm for colored objects, using the following steps:
1) take each frame of the video;
2) convert from BGR to HSV color-space;
3) threshold the HSV image for a range of color values (creating a binary mask);
4) erase everything in the original image except the mask.

In [ ]:
# TODO